PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "buildings" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar);
INSERT INTO "buildings" VALUES(1,'Big Bottle');
CREATE TABLE "floors" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "building_id" integer, "number" integer);
INSERT INTO "floors" VALUES(1,1,1);
INSERT INTO "floors" VALUES(2,1,2);
CREATE TABLE "apartments" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "floor_id" integer, "external_id" varchar);
INSERT INTO "apartments" VALUES(1,1,'101#B1');
INSERT INTO "apartments" VALUES(2,1,'102#B1');
INSERT INTO "apartments" VALUES(3,2,'201#B1');
CREATE TABLE "residents" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "apartment_id" integer, "external_id" varchar, "first_name" varchar, "last_name" varchar, "email" varchar, "phone_number" varchar);
INSERT INTO "residents" VALUES(1,1,'t0172185','Ricky','Pagan','irickpag@gmail.com','917-769-954');
INSERT INTO "residents" VALUES(2,1,'t0173470','unknown','Toinon','veronese@juno.com','212-679-238');
INSERT INTO "residents" VALUES(3,2,'t0174040','Marlisse','Martinez','marlimar15@yahoo.com','917-439-073');
INSERT INTO "residents" VALUES(4,2,'t0171702','unknown','Callahan','danny0324@yahoo.com','unknown');
INSERT INTO "residents" VALUES(5,3,'t0172293','Jonathan','DeLeon','jdforextrade@gmail.com','unknown');
CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
INSERT INTO "ar_internal_metadata" VALUES('environment','default_env','2017-03-23 17:53:35.208118','2017-03-23 17:53:35.208118');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('buildings',1);
INSERT INTO "sqlite_sequence" VALUES('floors',2);
INSERT INTO "sqlite_sequence" VALUES('apartments',3);
INSERT INTO "sqlite_sequence" VALUES('residents',5);
COMMIT;
